[package]
name = "chess-rest-api-rust-pleco"
version = "0.1.0"
edition = "2024"

[dependencies]
pleco = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.47.1", features = ["full"] }
shakmaty = "0.29.4"
lambda_http = "0.10"
